import type { Fork } from "./types"

export const forksData: Fork[] = [
  // Live / Launched forks
  {
    id: "felix",
    name: "Felix",
    description: "Liquity V2 fork on Hyperliquid",
    chain: "Hyperliquid",
    status: "launched",
    stablecoin: "feUSD",
    governanceToken: "N/A",
    website: "https://usefelix.xyz",
    docs: "https://usefelix.gitbook.io",
  },
  {
    id: "quill-finance",
    name: "Quill Finance",
    description: "Liquity V2 fork on Scroll",
    chain: "Scroll",
    status: "launched",
    stablecoin: "USDQ",
    governanceToken: "QUILL",
    website: "https://quill.finance",
    docs: "https://quill-finance.gitbook.io",
  },

  // Scheduled forks (launching soon)
  {
    id: "asymmetry-finance",
    name: "Asymmetry Finance",
    description: "Liquity V2 fork on Ethereum Mainnet",
    chain: "Ethereum",
    status: "scheduled",
    stablecoin: "USDaf",
    governanceToken: "ASF",
    website: "https://asymmetry.finance",
    docs: "https://docs.asymmetry.finance",
    launchDate: "Coming soon",
  },
  {
    id: "ironclad-finance",
    name: "Ironclad Finance",
    description: "Liquity V2 fork on Base",
    chain: "Base",
    status: "scheduled",
    stablecoin: "iUSD",
    governanceToken: "ICL",
    website: "https://ironclad.finance",
    docs: "https://docs.ironclad.finance",
    launchDate: "Coming soon",
  },
  {
    id: "ebisu-money",
    name: "Ebisu Money",
    description: "Liquity V2 fork on Ethereum Mainnet",
    chain: "Ethereum",
    status: "scheduled",
    stablecoin: "ebUSD",
    governanceToken: "EBISU",
    website: "https://ebisu.money",
    docs: "https://ebisu.money/",
    launchDate: "Coming soon",
  },
  {
    id: "aesyx",
    name: "Aesyx",
    description: "Liquity V2 fork on Avalanche",
    chain: "Avalanche",
    status: "scheduled",
    stablecoin: "USXY",
    governanceToken: "SXY",
    website: "https://aesyx.fi",
    docs: "https://docs.aesyx.fi",
    launchDate: "Coming soon",
  },
  {
    id: "nerite",
    name: "Nerite",
    description: "Liquity V2 fork on Arbitrum",
    chain: "Arbitrum",
    status: "scheduled",
    stablecoin: "USDN",
    governanceToken: "NERI",
    website: "https://nerite.org",
    docs: "https://docs.nerite.org/",
    launchDate: "Launching soon",
  },
  {
    id: "orki-finance",
    name: "Orki Finance",
    description: "Liquity V2 fork on Swell",
    chain: "Swell",
    status: "scheduled",
    stablecoin: "USDK",
    governanceToken: "ORKI",
    website: "https://www.orki.finance/",
    docs: "https://bento.me/orkifi",
    launchDate: "Launching soon",
  },

  // Unscheduled forks
  {
    id: "spiceusd",
    name: "SpiceUSD",
    description: "Liquity V2 fork on Blast",
    chain: "Blast",
    status: "unscheduled",
    stablecoin: "SUSD",
    governanceToken: "SPICE",
    website: "https://spiceusd.xyz",
    docs: "https://docs.spiceusd.xyz",
  },
  {
    id: "defi-dollar",
    name: "DeFi Dollar",
    description: "Liquity V2 fork on Ethereum Mainnet",
    chain: "Ethereum",
    status: "unscheduled",
    stablecoin: "DUSD",
    governanceToken: "DEFI",
    website: "https://defidollar.io",
    docs: "https://docs.defidollar.io",
  },
  {
    id: "beraborrow",
    name: "Beraborrow",
    description: "Liquity V2 fork on Berachain",
    chain: "Berachain",
    status: "unscheduled",
    stablecoin: "NECT",
    governanceToken: "POLLEN",
    website: "https://beraborrow.com",
    docs: "https://beraborrow.gitbook.io",
  },
  {
    id: "virtue",
    name: "Virtue",
    description: "Liquity V2 fork on IOTA",
    chain: "IOTA",
    status: "unscheduled",
    stablecoin: "vUSD",
    governanceToken: "TBD",
    website: "https://virtue.money",
    docs: "https://docs.virtue.money/",
  },
]
