import type { Fork } from "./types"

export const forksData: Fork[] = [
  // Live / Launched forks
  {
    id: "felix",
    name: "Felix",
    description: "Liquity V2 fork on Hyperliquid",
    chain: "Hyperliquid",
    status: "launched",
    stablecoin: "feUSD",
    governanceToken: "N/A",
    website: "https://usefelix.xyz",
    docs: "https://usefelix.gitbook.io",
    twitter: "https://x.com/felixprotocol",
    logoUrl: "/felix-logo.png",
    collaterals: ["HYPE", "UBTC", "kHYPE", "wstHYPE"],
    longDescription:
      "Felix is a suite of onchain borrowing and lending products running on Hyperliquid L1. Their goal is to let anyone unlock liquidity or earn yield in a secure, risk-adjusted, and friction-free way.",
  },
  {
    id: "quill-finance",
    name: "Quill Finance",
    description: "Liquity V2 fork on Scroll",
    chain: "Scroll",
    status: "launched",
    stablecoin: "USDQ",
    governanceToken: "QUILL",
    website: "https://quill.finance",
    docs: "https://quill-finance.gitbook.io",
    twitter: "https://x.com/QuillFi",
    logoUrl: "/quill-logo.png",
    rewards: {
      title: "Rewards Program",
      url: "https://medium.com/@QuillFi/fueling-defi-quills-revamped-incentives-programs-926e4ffd9034",
    },
    collaterals: ["wstETH", "wETH", "weETH", "SCR"],
    longDescription:
      "Quill is a fork of the Liquity v2 protocol, built to enhance the capabilities of decentralized finance (DeFi) while integrating specific features tailored for its ecosystem. This relationship allows Quill to leverage Liquity's robust mechanisms for minting stablecoins and managing collateralized debt positions while introducing unique improvements and innovations.",
  },
  {
    id: "orki-finance",
    name: "Orki Finance",
    description: "Liquity V2 fork on Swell",
    chain: "Swell",
    status: "launched",
    stablecoin: "USDK",
    governanceToken: "ORKI",
    website: "https://www.orki.finance/",
    docs: "https://bento.me/orkifi",
    twitter: "https://x.com/OrkiFi",
    logoUrl: "/orki-logo.png",
    collaterals: ["ETH", "swETH", "rswETH", "weETH", "Swell"],
    longDescription:
      "Orki Finance is a permissionless credit layer and stablecoin protocol with a focus on Liquid Staking and Restaking Tokens on Swell Network.",
  },
  {
    id: "nerite",
    name: "Nerite",
    description: "Liquity V2 fork on Arbitrum",
    chain: "Arbitrum",
    status: "launched",
    stablecoin: "USND",
    governanceToken: "NERI",
    website: "https://nerite.org",
    docs: "https://docs.nerite.org/",
    twitter: "https://x.com/neriteorg",
    logoUrl: "/nerite-logo.png",
    rewards: {
      title: "Rewards Program",
      url: "https://www.nerite.org/writing/bold-incentive-program",
    },
    collaterals: ["WETH", "wstETH", "rETH", "rsETH", "weETH", "tBTC", "COMP", "ARB"],
    longDescription:
      "Nerite is a decentralized borrowing protocol that lets users deposit ETH, LSTs, and ARB as collateral, and mint the stablecoin NUSD at an interest rate depositors choose. Nerite is based on Liquity v2.",
  },
  {
    id: "aesyx",
    name: "Aesyx",
    description: "Liquity V2 fork on Avalanche",
    chain: "Avalanche",
    status: "launched",
    stablecoin: "USXY",
    governanceToken: "SXY",
    website: "https://aesyx.fi",
    docs: "https://docs.aesyx.fi",
    twitter: "https://x.com/Aesyx_Fi",
    logoUrl: "/aesyx-logo.png",
    rewards: {
      title: "Rewards Program",
      url: "https://x.com/LiquityProtocol/status/1954927945992286598",
    },
    collaterals: ["BTC.b", "AVAX", "LSTs"],
    longDescription:
      "Aesyx is a decentralized borrowing protocol on Avalanche that allows users to mint USXY stablecoins against various collaterals including BTC.b, AVAX, and Liquid Staking Tokens.",
  },
  {
    id: "ebisu-money",
    name: "Ebisu Money",
    description: "Liquity V2 fork on Ethereum Mainnet",
    chain: "Ethereum",
    status: "launched",
    stablecoin: "ebUSD",
    governanceToken: "EBISU",
    website: "https://ebisu.money",
    docs: "https://ebisu.gitbook.io/ebisu-money/",
    twitter: "https://x.com/ebisu_finance",
    logoUrl: "/ebisu-logo.png",
    collaterals: ["WBTC", "LBTC", "sUSDe", "weETH"],
    longDescription:
      "Ebisu Money is a decentralized borrowing protocol that allows users to mint ebUSD stablecoins against various collaterals on Ethereum, including Liquid Restaking Tokens.",
  },
  {
    id: "defi-dollar",
    name: "DeFi Dollar",
    description: "Liquity V2 fork on Ethereum Mainnet",
    chain: "Ethereum",
    status: "launched",
    stablecoin: "USDFI",
    governanceToken: "DEFI",
    website: "https://defidollar.io",
    docs: "https://docs.defidollar.io",
    twitter: "https://x.com/DeFiDollarIO",
    logoUrl: "/defi-dollar-logo.png",
    rewards: {
      title: "Rewards Program",
      url: "https://x.com/DeFiDollarIO/status/1950944516007219581",
    },
    collaterals: ["WBTC", "LINK", "UNI", "AAVE", "LDO", "CRV", "FRAX", "SKY", "LQTY", "YFI"],
    longDescription:
      "DeFi Dollar is a decentralized borrowing protocol on Ethereum that allows users to mint USDFI stablecoins against various collaterals, including LQTY.",
  },

  // Scheduled forks (launching soon)
  {
    id: "asymmetry-finance",
    name: "Asymmetry Finance",
    description: "Liquity V2 fork on Ethereum Mainnet",
    chain: "Ethereum",
    status: "launched",
    stablecoin: "USDaf",
    governanceToken: "ASF",
    website: "https://asymmetry.finance",
    docs: "https://docs.asymmetry.finance",
    twitter: "https://x.com/asymmetryfin",
    logoUrl: "/asymmetry-logo.png",
    collaterals: ["wBTC", "tBTC", "sfrxUSD", "sUSDS", "scrvUSD", "ysyBOLD"],
    longDescription:
      "Asymmetry Finance is a decentralized borrowing protocol that allows users to mint USDaf stablecoins against various Bitcoin-backed and yield-bearing stablecoin collaterals on Ethereum.",
  },
  {
    id: "ironclad-finance",
    name: "Ironclad Finance",
    description: "Liquity V2 fork on Base",
    chain: "Base",
    status: "scheduled",
    stablecoin: "iUSD",
    governanceToken: "ICL",
    website: "https://ironclad.finance",
    docs: "https://docs.ironclad.finance",
    twitter: "https://x.com/IroncladFinance",
    logoUrl: "/ironclad-logo.png",
    launchDate: "Coming soon",
    hidden: true,
  },
  {
    id: "soneta",
    name: "Soneta",
    description: "Liquity V2 fork on Sonic",
    chain: "Sonic",
    status: "scheduled",
    stablecoin: "ONE",
    governanceToken: "STA",
    website: "https://www.soneta.xyz/",
    docs: "https://docs.soneta.xyz/",
    twitter: "https://x.com/soneta_xyz",
    logoUrl: "/soneta-logo.png",
    collaterals: ["S", "sTS", "wOS", "LBTC"],
    longDescription:
      "Liquity V2 fork on Sonic blockchain enabling users to mint the ONE stablecoin against various collaterals.",
  },
  {
    id: "saga-fork",
    name: "Mustang Finance",
    description: "Liquity V2 fork on Saga",
    chain: "Saga",
    status: "scheduled",
    stablecoin: "MUST",
    governanceToken: "N/A",
    website: "https://www.must.finance/",
    docs: null,
    twitter: "https://x.com/mustangfinance",
    logoUrl: "/mustang-logo.jpg",
    collaterals: ["ETH", "rETH", "tBTC", "FBTC", "SAGA"],
    longDescription:
      "Mustang Finance is a Liquity V2 fork on the Saga blockchain, providing decentralized credit with unbridled speed. Users can mint MUST stablecoins against ETH, rETH, and tBTC collaterals.",
  },

  // Unscheduled forks
  {
    id: "alpen",
    name: "Alpen",
    description: "Liquity V2 fork on Strata",
    chain: "Strata",
    status: "unscheduled",
    stablecoin: "BTD",
    governanceToken: "N/A",
    website: "https://www.alpenlabs.io/",
    docs: "https://docs.alpenlabs.io/",
    twitter: "https://x.com/AlpenLabs",
    logoUrl: "/alpen-logo.png",
    longDescription:
      "BTD will deploy Liquity V2 with BTC as the sole collateral on Alpen's Bitcoin ZK rollup with immutable code from the moment of deployment.",
  },
  {
    id: "beraborrow",
    name: "Beraborrow",
    description: "Liquity V1 fork on Berachain",
    chain: "Berachain",
    status: "unscheduled",
    stablecoin: "NECT",
    governanceToken: "POLLEN",
    website: "https://beraborrow.com",
    docs: "https://beraborrow.gitbook.io",
    twitter: "https://x.com/beraborrow",
    logoUrl: "/beraborrow-logo.png",
    longDescription:
      "Beraborrow unlocks instant liquidity against Berachain assets through the first PoL powered stablecoin, Nectar ($NECT). Built with simplicity and flexibility at its core, Beraborrow is designed to maximise opportunities for users without forcing them to sacrifice yield.",
  },
  {
    id: "spiceusd",
    name: "SpiceUSD",
    description: "Liquity V2 fork on Blast",
    chain: "Blast",
    status: "unscheduled",
    stablecoin: "SUSD",
    governanceToken: "SPICE",
    website: "https://spiceusd.xyz",
    docs: "https://docs.spiceusd.xyz",
    twitter: "https://x.com/spiceusd",
    logoUrl: "/spiceusd-logo.png",
    hidden: true,
    collaterals: ["ETH", "BLAST", "USDB", "THRUST", "HYPER", "FNX"],
    longDescription:
      "SpiceUSD is a friendly fork of Liquity V2, a decentralized collateralized debt position (CDP) protocol offering security, stability, and advanced features like user-defined, market-driven interest rates.",
  },
  {
    id: "pigeon",
    name: "Pigeon/Hanzo",
    description: "Liquity V2 fork on Katana",
    chain: "Katana",
    status: "unscheduled",
    stablecoin: "–",
    governanceToken: "N/A",
    website: null,
    docs: null,
    logoUrl: "/katana-logo.jpg",
    longDescription: "Pigeon/Hanzo is a Liquity V2 fork on the Katana blockchain.",
  },
  {
    id: "vermillion",
    name: "Vermillion",
    description: "Liquity V2 fork on Sei",
    chain: "Sei",
    status: "unscheduled",
    stablecoin: "–",
    governanceToken: "N/A",
    website: null,
    docs: null,
    twitter: "https://x.com/VermillionFi",
    logoUrl: "/vermillion-logo.jpg",
    longDescription: "Vermillion is a Liquity V2 fork on the Sei blockchain.",
  },
  {
    id: "gyoza",
    name: "Gyoza",
    description: "Liquity V2 fork on Ronin",
    chain: "Ronin",
    status: "unscheduled",
    stablecoin: "gyUSD",
    governanceToken: "N/A",
    website: "https://gyoza.finance/",
    twitter: "https://x.com/gyozafinance",
    docs: null,
    logoUrl: "/gyoza-logo.jpg",
    collaterals: ["ETH", "RON", "AXS", "LRON", "FBTC", "rETH"],
    longDescription:
      "Gyoza is a Liquity V2 fork on the Ronin blockchain, allowing users to mint gyUSD stablecoins against various collaterals including ETH, RON, AXS, and other Ronin ecosystem tokens.",
  },
]
